### ISSUE TITLE
DATABASE=cassandra fails in some cases

### ISSUE THREAD

**Issue by dmorgantini** [cliftonc/seguir#15]
Account and application management runs against postgres regardless of DATABASE=cassandra

**Comment by cliftonc** [comment]
This is still an issue, there appears to be no simple resolution, so I will modify the way the tests work with Cassandra so that it truncates tables in an existing keyspace wherever possible, vs re-creating clean keyspaces.

**Comment by cliftonc** [comment]
This now looks good with the commit above, travis seems to pass every time now, will see how it likes schema migrations (coded to handle it), but will close for now.
