### ISSUE TITLE
Remove posts when unfollowing a user

### ISSUE THREAD

**Issue by cliftonc** [cliftonc/seguir#20]
When you unfollow a user, you should ideally also not show their posts in the users feed - this is what all the other social networks do. 

Changes (wip):

1.  We should add an extra field into the feed - 'fromFollow' with the follow guid so that we can find them easily - so when creating a post in a followers feed we set this field.

Now, we have two options:

1.  Get a list of all of everyone a user follows when rendering their feed, filter out anything from a follow relationship that isn't in that list.  This has implications for pagination as you are hiding things that would be rendered (likely not to be a serious problem).  The list of everyone a user follows could get very large.  

  1.a.  Alternative is to check on every single post as you render the feed to see if the relationship is still active (perhaps with a cache  to speed it up a little for relationships you've already checked).  

2.  Go and delete and / or update the items in the feed after the follow is removed.  This has implications in that Cassandra doesn't really do deletes or updates well, and this will be a really big dataset, really fast.

**Comment by dmorgantini** [comment]
I think that option 1 seems like the sanest idea to me.  If we can find a decent way to do this filtering it can solve a few potential long term requirements such as:

* show fewer of these posts
* show more of these posts
* collapse like items into a single item (ie: John & six others have followed you)

**Comment by cliftonc** [comment]
Agreed solution was to:

- Leave posts in peoples feeds, don't try and go delete wide follower graphs based on the follow key.  (note we do this when a specific item is deleted - a follow or post - but in this case we are deleting by item id - which is a key in the newsfeed).  
- When retreiving a post (via the expander: https://github.com/cliftonc/seguir/blob/master/api/feed/index.js#L222) we will check if the post is from someone you follow (e.g. you are not the author), and if so, check that the follow relationship still exists.
- If the follow relationship does not exist, then silently drop the post from the feed.

We can revisit this if it doesn't scale.

**Comment by cliftonc** [comment]
This has now been completed in the initial form as above in release 0.7.1.  We can revisit and see if deleting the items vs filtering is a better idea once we are live and can see any performance impacts.
