### ISSUE TITLE
Add counters construct to efficiently store total follower counts

### ISSUE THREAD

**Issue by cliftonc** [cliftonc/seguir#21]
Not much more we need to add, incorrectly referenced issue in commit:  86468b05e2bb3c817cc15fa03e8844c7dc57c444

**Comment by cliftonc** [comment]
https://github.com/cliftonc/seguir/commit/00682f63e2c4707b0400e145556057cfc8d11902

**Comment by dmorgantini** [comment]
Looks sane (ish) to me.  Let's go through tomorrow.

**Comment by cliftonc** [comment]
Closing - this is done and published.
