### ISSUE TITLE
Follow events not being propagated to followers' feeds

### ISSUE THREAD

**Issue by jonnywyatt** [cliftonc/seguir#28]
Follow steps 1 and 2 of the [home page scenarios](https://github.com/tes/social-team/wiki/Home-page-and-Followers-page-Scenarios)
danyrose should see the follow event added to his feed, but it isn't. (ie the entry added to tes_seguir_service_social_hub.feed_timeline)

**Comment by cliftonc** [comment]
At the moment it only adds it to the feed of the user being followed, which then copies it out to the followers feed (as they are a follower).  

What it doesn't do is add it directly to the followers feed (e.g. send it out to all of their followers).

**Comment by cliftonc** [comment]
Not saying this is correct btw - just saying that it is what it is doing.

https://github.com/cliftonc/seguir/blob/master/api/follow/index.js#L49

**Comment by gajjargaurav** [comment]
the follow logic used for above mentioned scenarios is on https://github.com/tes/social-team/wiki/Follow-Facts.

**Comment by cliftonc** [comment]
This was fixed and pushed to NPM in 0.5.5, later refactored to be a bit easier on the eyes in 0.6.0 (which also has a refactor of how the client auth works to make it easier to update the id / secrets in running environments.
