### ISSUE TITLE
remove follower doesn't seem to work as advertised

### ISSUE THREAD

**Issue by dmorgantini** [cliftonc/seguir#38]
There doesn't seem like there is anyway this could work:

https://github.com/cliftonc/seguir/blob/master/server/index.js#L701

**Comment by cliftonc** [comment]
It basically enforces the rule 'you can only un-follow someone you have followed'.

In the follower table:

- user = the user being followed.
- user_follower = the user doing the following.

Hence when removing a follower, you can only perform the action if you ```req.liu``` are the ```user_follower```.

**Comment by cliftonc** [comment]
In hindsight it may have been better to model the follow structure the other way around - ```user``` and ```user_following```.

**Comment by dmorgantini** [comment]
Understood. The documentation only specifies user & user_follower, not liu.
Thus my confusion.

On Friday, July 31, 2015, Clifton Cunningham <notifications@github.com>
wrote:

> In hindsight it may have been better to model the follow structure the
> other way around - user and user_following.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cliftonc/seguir/issues/38#issuecomment-126570434>.
>


-- 
Sent from Gmail Mobile

**Comment by cliftonc** [comment]
For future reference:

http://cliftonc.github.io/seguir/client/#api-Following-removeFollower
http://cliftonc.github.io/seguir/client/#api-Following-unFollowUser

**Comment by dmorgantini** [comment]
Ha!
