### ISSUE TITLE
Performance in real world

### ISSUE THREAD

**Issue by cliftonc** [cliftonc/seguir#44]
Ok ... so we are now starting to collect some real data, and the current fan out of queries from the feed to a lot of cassandra GETs is slowwww.

<img width="1162" alt="screen shot 2015-08-14 at 10 07 25" src="https://cloud.githubusercontent.com/assets/239305/9270979/e4b91394-426d-11e5-9a06-7b9ddf16caf8.png">

Open issue to discuss solutions.

**Comment by cliftonc** [comment]
### Option 1 - Redis as a LRU cache

Introduce a layer, directly into the Cassandra DB layer, that acts as an object cache (old school Hibernate style) in Redis.  It can both store and invalidate the cache, and we can do it all with TTLs so we don't kill the server and end up storing the world in there.

Pros:  No change to the API, redis is already there.
Cons:  In this model, we should probably just switch to Postgres and get on with our lives.

**Comment by cliftonc** [comment]
## Option 2 - Denormalise data into feed tables

Store the user and item data in the feed table as an additional column, so that it isn't retrieved as part of the feed rendering pipeline.

Pros:  No extra moving parts.
Cons:  Means that updating items becomes v. costly as you potentially need to scan every users feed (e.g. changing a user name or updating a post).

**Comment by cliftonc** [comment]
## Option 3 - Move to Postgres

Postgres uses joins to get the data out of the feed and all the items in one go, so it doesn't do N+1 gets.  So we should just switch to it.

Pros:  All the tests will be faster and wont break.
Cons:  Longevity as we get feeds from millions of TES users in it?

**Comment by dmorgantini** [comment]
WWFBD?

**Comment by dmorgantini** [comment]
A much cheaper - short term fix would be to do an in memory user request cache - ie: 90% of the posts come from the same user so for each request only get any user once.

**Comment by cliftonc** [comment]
https://github.com/cliftonc/seguir/pull/45

**Comment by cliftonc** [comment]
Ok - I've merged the redis cache, will close this for now, and re-open if we have issues with that approach.
