### ISSUE TITLE
Allow array of followers in AddUser

### ISSUE THREAD

**Issue by dmorgantini** [cliftonc/seguir#5]
If provided, Sequir should pre-fill the new users news feed with items from the users within a follower array. The amount of time to populate should/could be configurable within the sequir application.

Alternatively this could be done within the wrapping application.

**Comment by cliftonc** [comment]
:+1: agree, this is a very useful feature.  I propose the following as the content of the post to create a new user:

```json
{
  "altid":"1234", 
  "username": "cliftonc",
  "userdata": {
     "avatar": "/blah/123.jpg" 
  },
  "follow": {
    "users": ["dmorgantini","tes","tesgeography"],
    "backfill": "3d"
  } 
}
```

The backfill would have a sensible default - say 1 day - and the follow block is entirely optional.  This means that the config is kept out of seguir and in the users control.

Feels cleaner to have the users specified by name vs alternate ID or seguirID, but we can use the standard 'coerce' code to allow any of the three to be provided.

**Comment by cliftonc** [comment]
In progress:  https://github.com/cliftonc/seguir/commit/bc4a9300a9cad8f99d2a427c33125f47f346fa28

**Comment by cliftonc** [comment]
Now working, as per the additional (optional) initialise property when adding a user.

For example see:

https://github.com/cliftonc/seguir/blob/master/tests/acceptance/server.test.js#L702

**Comment by cliftonc** [comment]
Will leave this open until we prove it works in the real world.

**Comment by dmorgantini** [comment]
The documentation does not seem to have been updated :)

**Comment by cliftonc** [comment]
I need to figure out how to add sample inputs into the apidocs - it is a bit crap really, may be better to migrate to swagger or something better.

**Comment by dmorgantini** [comment]
Can you also publish to npm? :-)

**Comment by cliftonc** [comment]
Ok - will just merge the changes in the https://github.com/cliftonc/seguir/tree/multi-database branch first, and then publish.

**Comment by cliftonc** [comment]
https://github.com/cliftonc/seguir/pull/6

**Comment by dmorgantini** [comment]
I actually spent some time thinking about this... would it not be a cleaner api if we add a 'backfill' value to the follow api rather than shoe horning into the add user api?

**Comment by cliftonc** [comment]
Perhaps, but then the client needs to do all the coordination and make multiple requests, vs a single call.

I think the best answer is to expose the underlying methods used to do the user initialisation version, and then you can call each step in sequence on the client at any point.

This way you can choose which approach you want to use?

**Comment by dmorgantini** [comment]
So a backfill api of some sort?

**Comment by cliftonc** [comment]
Maybe keep it as follow user but add an optional parameter which is backfill, then just wire it up to the functions used to do the addUser initialisation version.

This is the point I consider re writing every api to accept options, callback vs named params ... (I won't!).

**Comment by cliftonc** [comment]
Ok - this is now done, the followUser function now accepts the same optional backfill parameter.

http://cliftonc.github.io/seguir/client/#api-Following-followUser
