### ISSUE TITLE
Seguir can't post to a different user's feed

### ISSUE THREAD

**Issue by dmorgantini** [cliftonc/seguir#58]
Currently the addPost function https://github.com/cliftonc/seguir/commit/3ffe1cabe8e87bf1b641013dfdb5d1502eec7b5d#diff-380a9fa787e7824c57c21f95c24f707cR18 does not allow you to post onto another user's wall only your own.

I suggest creating a new function called 'addPostToFeed' which takes an additional field and posts to that user's feed based on visibility.

**Comment by cliftonc** [comment]
Assuming we have David and Clifton, and Clifton wants to post 'Hello World' on David's feed without David following Clifton, and have only David see it.

This new function would basically wrap two existing APIs:

1.  ```post.addPost``` - user: clifton, visibility: personal
2.  ```feed.upsertTimeline``` - user = david, item = post in step #1.

```
upsertTimeline(keyspace, 'feed_timeline', user, item.item, item.type, item.time, item.visibility, null, cb);
```

We'd need to expose ```upsertTimeline``` in the feed API.  

Why do we want to do this again?

**Comment by dmorgantini** [comment]
Cause all the cool kids let you post on somebody else's wall.

On Tuesday, September 29, 2015, Clifton Cunningham <notifications@github.com>
wrote:

> Assuming we have David and Clifton, and Clifton wants to post 'Hello
> World' on David's feed without David following Clifton, and have only David
> see it.
>
> This new function would basically wrap two existing APIs:
>
>    1. post.addPost - user: clifton, visibility: personal
>    2. feed.upsertTimeline - user = david, item = post in step #1
>    <https://github.com/cliftonc/seguir/issues/1>.
>
> upsertTimeline(keyspace, 'feed_timeline', user, item.item, item.type, item.time, item.visibility, null, cb);
>
> We'd need to expose upsertTimeline in the feed API.
>
> Why do we want to do this again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cliftonc/seguir/issues/58#issuecomment-144057624>.
>


-- 
Sent from Gmail Mobile

**Comment by cliftonc** [comment]
Do you think it is ok just to export ```upsertTimeline``` and let the consumer call both, or expose a wrapper to both in the seguir ```post``` api?

**Comment by dmorgantini** [comment]
I'd prefer to wrap it - but not bothered :-)

**Comment by dmorgantini** [comment]
No longer needed.
